services:
  usermanagement-application:
    image: usermanagemnet-application-image:latest
    build:
     context: .
     dockerfile: Dockerfile
    ports:
     - "8082:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/userdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Root@123
    depends_on:
     - mysql-db
    networks:
    - user-network

  mysql-db:
    image: mysql:8.0
    ports:
     - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Root@123
      MYSQL_DATABSE: userdb
    volumes:
     - mysql-data:/var/lib/mysql
    networks:
    - user-network

volumes:
 mysql-data:

networks:
 user-network:
  driver: bridge